### ISSUE TITLE
test profile yaml 을 추가하고, embed h2 를 사용하도록 추가

### ISSUE THREAD

**Issue by bruce-daeyeong-kim** [sk-eugene/devide-integration-test#3]
@SpringBootTest 가 동작하지 않는 이유는 DB 설정 오류로 보임
통합 테스트 시 실제 DB 를 사용 할 필요는 없으므로
embed h2 database 를 활용하도록 하면 될 듯함

TODO
- test profile yaml 을 추가하고, embed h2 를 사용하도록 추가

목표
- docker db 가 떠 있지 않아도, active profile= test 일 때 스프링 어플리케이션이 뜨도록 함

**Comment by sk-eugene** [comment]
작업 완료
